server:
  port: 8080

spring:
  application:
    name: spring-gateway
  cloud:
    gateway:
      routes:

        - id: resource-service-route
          uri: lb://resource-service/
          predicates:
            - Path=/resources/**
            - Method=POST

        - id: song-service-route
          uri: lb://song-service/
          predicates:
            - Path=/songs/**
            - Method=GET

        - id: 403-route
          uri: no://op
          predicates:
            - Path=/**
          filters:
            - SetStatus=403

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka
    instance:
    preferIpAddress: true

logging:
  level:
    org.springframework.cloud.gateway.handler.RoutePredicateHandlerMapping: DEBUG